version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=superSecret123
      - DB_NAME=my-app_development
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superSecret123
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
